name: 'music_semantic_metrics_lab'
version: '1.0.0'
config-version: 2

profile: 'music_semantic_metrics_lab'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  music_semantic_metrics_lab:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: transform
    marts:
      +materialized: table
      +schema: marts
